import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./styles.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <div className={inter.className + " flex flex-col justify-between h-[100vh]"}>
        <div data-tauri-drag-region className="titlebar"/>
        {children}
      </div>
      </body>
    </html>
  );
}
